title: "UCSB CS32"
course: "CS32"
github_url: https://github.com/ucsb-cs32/ucsb-cs32.github.io
course_title: "Object Oriented Design and Implementation"
catalog_desc_url: http://www.cs.ucsb.edu/education/courses/cmpsc-32

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/


#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: topic

  - scope:
      path: ""
      type: resources
    values:
      layout: topic
