plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs32.github.io # the base hostname & protocol for your site
baseurl: "/"  # the subpath of your site "/" for main, "/w19" for instance

title: "UCSB CS32"
course: "CS32"
qtr: "W19"
github_url: https://github.com/ucsb-cs32/ucsb-cs32.github.io
course_title: "Object Oriented Design and Implementation"
catalog_desc_url: http://www.cs.ucsb.edu/education/courses/cmpsc-32

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/


#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include: ['_pages']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: default

  - scope:
      path: ""
      type: resources
    values:
      layout: default
